routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('index');

Route::resource('user', 'UserController')->except(['index']);
Route::resource('mobile', 'MobileController');

app/Mobile.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Mobile extends Model
{
    public function user() {
        return $this->belongsTo(User::class);
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class User extends Model
{
    public function mobiles() {
        return $this->hasMany(Mobile::class);
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use App\User;
use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::latest()->get();
        return view('welcome', compact('users'));
    }
}

app/Http/Controllers/MobileController.php
<?php

namespace App\Http\Controllers;

use App\Mobile;
use App\User;
use Brian2694\Toastr\Facades\Toastr;
use Illuminate\Http\Request;

class MobileController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $mobiles = Mobile::latest()->get();
        return view('mobile.index', compact('mobiles'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $users = User::all();
        return view('mobile.insert', compact('users'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'phone' => 'required',
            'user' => 'required'
        ]);

        $mobile = new Mobile();
        $mobile->number = $request->phone;
        $mobile->user_id = $request->user;
        $mobile->save();

        Toastr::success('Number successfully saved...', 'Success');
        return back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $mobile = Mobile::findOrFail($id);
        return view('mobile.show', compact('mobile'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $mobile = Mobile::findOrFail($id);
        return view('mobile.edit', compact('mobile'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'phone' => 'required',
            'user' => 'required'
        ]);

        $mobile = Mobile::findOrFail($id);
        $mobile->number = $request->phone;
        $mobile->user_id = $request->user;
        $mobile->save();

        Toastr::success('Number successfully updated...', 'Success');
        return redirect(route('mobile.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $mobile = Mobile::findOrFail($id);
        $mobile->delete();

        Toastr::success('Number successfully deleted...', 'Success');
        return back();
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Mobile;
use App\User;
use Brian2694\Toastr\Facades\Toastr;
use Illuminate\Http\Request;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('insert');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|string'
        ]);

        $user = new User();
        $user->name = $request->name;
        $user->save();

        Toastr::success('User successfully saved...', 'Success');
        return back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $user = User::findOrFail($id);
        return view('show', compact('user'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::findOrFail($id);
        return view('edit', compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'name' => 'required|string'
        ]);

        $user = User::findOrFail($id);
        $user->name = $request->name;
        $user->save();

        Toastr::success('User successfully updated...', 'Success');
        return redirect(route('index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = User::findOrFail($id);
        $user->delete();
        $mobile = Mobile::findOrFail($id);
        $user->mobiles()->delete($mobile);
        $mobile->delete();

        Toastr::success('User successfully deleted...', 'Success');
        return back();
    }
}

resources/views/edit.blade.php
@extends('layouts.app')

@section('site-title', 'One to Many RelationShip')


@section('header-title', 'ONE TO MANY RELATIONSHIP')


@section('main-content')
    <div class="card">
        <div class="card-header bg-secondary">
            <h3 class="card-title">Insert Data</h3>
            <a href="{{ route('index') }}" class="btn btn-primary float-right" style="margin-top: -40px;">Back</a>
        </div>
        <div class="card-body">
            <form action="{{ route('user.update', $user->id) }}" method="post">
                @csrf
                @method("PUT")
                <div class="form-group row">
                    <label for="name" class="col-sm-2 col-form-label">Name</label>
                    <div class="col-sm-10">
                        <input type="text" name="name" class="form-control" id="name" placeholder="Name" value="{{ $user->name }}">
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-sm-10">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </div>
                <form/>
        </div>
    </div>
@endsection

resources/views/insert.blade.php
@extends('layouts.app')

@section('site-title', 'One to Many RelationShip')


@section('header-title', 'ONE TO MANY RELATIONSHIP')


@section('main-content')
    <div class="card">
        <div class="card-header bg-secondary">
            <h3 class="card-title">Insert Data</h3>
            <a href="{{ route('index') }}" class="btn btn-primary float-right" style="margin-top: -40px;">Back</a>
        </div>
        <div class="card-body">
            <form action="{{ route('user.store') }}" method="post">
                @csrf
                <div class="form-group row">
                    <label for="name" class="col-sm-2 col-form-label">Name</label>
                    <div class="col-sm-10">
                        <input type="text" name="name" class="form-control" id="name" value="{{ old('name') }}" placeholder="Name">
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-sm-10">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </div>
            <form/>
        </div>
    </div>
@endsection

resources/views/layouts/app.blade.php
@include('layouts.partials.header')

<div class="container mt-5">
    <div class="row">
        <div class="col-md-12">
            @yield('main-content')
        </div>
    </div>
</div>


@include('layouts.partials.footer')

resources/views/layouts/partials/footer.blade.php
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-footer" style="position: fixed;bottom: 0;">
                    &copy; {{ now()->year }} MI SHAJIB. ALL RIGHTS RESERVED.
                </div>
            </div>
        </div>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
<!-- Sweet Alert 2 -->
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@8.3.0/dist/sweetalert2.all.min.js"></script>
<!-- Sweet Alert 2 End -->
<!-- Toastr Js -->
<script src="http://cdn.bootcss.com/jquery/2.2.4/jquery.min.js"></script>
<script src="https://cdn.bootcss.com/toastr.js/latest/js/toastr.min.js"></script>
{!! Toastr::message() !!}
<!-- Toastr Js End -->
<script>
    @if($errors->any())
    @foreach($errors->all() as $error)
    toastr.error('{{ $error }}', 'Error', {
        closeButton: true,
        progressBar: true,
    });
    @endforeach
    @endif
</script>
@stack('js')

</body>
</html>

resources/views/layouts/partials/header.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>@yield('site-title', 'Enter title here')</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <!-- Toastr Css -->
    <link rel="stylesheet" href="https://cdn.bootcss.com/toastr.js/latest/css/toastr.min.css">
    <!-- Toastr Css End -->
</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="card bg-primary text-center mt-2">
                <div class="card-header">
                    <h2 class="card-title">
                        @yield('header-title', 'Enter Header Title Here')
                    </h2>
                </div>
            </div>
        </div>
    </div>
</div>

resources/views/mobile/edit.blade.php
@extends('layouts.app')

@section('site-title', 'One to Many RelationShip')


@section('header-title', 'ONE TO MANY RELATIONSHIP')


@section('main-content')
    <div class="card">
        <div class="card-header bg-secondary">
            <h3 class="card-title">Insert Data</h3>
            <a href="{{ route('mobile.index') }}" class="btn btn-primary float-right" style="margin-top: -40px;">Back</a>
        </div>
        <div class="card-body">
            <form action="{{ route('mobile.update', $mobile->id) }}" method="post">
                @csrf
                @method('PUT')
                <div class="form-group row">
                    <label for="number" class="col-sm-2 col-form-label">Number</label>
                    <div class="col-sm-10">
                        <input type="text" name="number" class="form-control" id="number" value="{{ $mobile->number }}" placeholder="Number">
                    </div>
                </div>

                <div class="form-group row">
                    <label for="user" class="col-sm-2 col-form-label">User</label>
                    <div class="col-sm-10">
                        <select name="user" id="user" class="custom-select my-1 mr-sm-2">
                            <option selected disabled>Choose...</option>
                                @forelse($users as $user)
                                    <option {{ $mobile->user_id == $user->id ? 'selected':'' }} value="{{ $user->id }}">{{ $user->name }}</option>
                                @empty
                                    <option disabled>No data found!!</option>
                                @endforelse
                        </select>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-sm-10">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </div>
                <form/>
        </div>
    </div>
@endsection

resources/views/mobile/index.blade.php
@extends('layouts.app')

@section('site-title', 'One to Many RelationShip')


@section('header-title', 'ONE TO MANY RELATIONSHIP')


@section('main-content')
    <div class="card">
        <div class="card-header bg-secondary">
            <h3 class="card-title">View All Numbers</h3>
            <a href="{{ route('mobile.create') }}" class="btn btn-primary float-right" style="margin-top: -40px;">Add New</a>
            <a href="{{ route('index') }}" class="btn btn-primary float-right" style="margin-top: -40px; margin-right: 100px;">Back</a>
        </div>
        <div class="card-body">
            <table class="table table-bordered table-dark text-center">
                <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Numbers</th>
                    <th scope="col">User</th>
                    <th scope="col">Action</th>
                </tr>
                </thead>
                <tbody>
                        @forelse($mobiles as $key=>$mobile)
                            <tr>
                                <td>{{ ++$key }}</td>
                                <td>{{ $mobile->number }}</td>
                                <td>{{ $mobile->user->name }}</td>
                                <td>
                                    <a href="{{ route('mobile.edit', $mobile->id) }}" class="btn btn-info btn-sm">
                                        <i class="fa fa-edit"></i>
                                    </a>

                                    <button onclick="deleteMobile({{ $mobile->id }})" class="btn btn-danger" type="button">
                                        <i class="fa fa-trash"></i>
                                    </button>
                                    <form id="delete-form-{{ $mobile->id }}" action="{{ route('mobile.destroy', $mobile->id) }}" method="POST" style="display: none;">
                                        @csrf
                                        @method('DELETE')
                                    </form>

                                    <a href="{{ route('mobile.show', $mobile->id) }}" class="btn btn-primary btn-sm">
                                        <i class="fa fa-eye"></i>
                                    </a>
                                </td>
                            </tr>
                        @empty
                            <tr>
                                <td colspan="3">No data found!</td>
                            </tr>
                        @endforelse

                </tbody>
            </table>
        </div>
    </div>
@endsection

@push('js')
    <script>
        function deleteMobile(id) {
            const swalWithBootstrapButtons = Swal.mixin({
                customClass: {
                    confirmButton: 'btn btn-success',
                    cancelButton: 'btn btn-danger'
                },
                buttonsStyling: false,
            })

            swalWithBootstrapButtons.fire({
                title: 'Are you sure?',
                text: "You won't be able to revert this!",
                type: 'warning',
                showCancelButton: true,
                confirmButtonText: 'Yes, delete it!',
                cancelButtonText: 'No, cancel!',
                reverseButtons: true
            }).then((result) => {
                if (result.value) {
                    event.preventDefault();
                    document.getElementById('delete-form-'+id).submit();
                } else if (
                    // Read more about handling dismissals
                    result.dismiss === Swal.DismissReason.cancel
                ) {
                    swalWithBootstrapButtons.fire(
                        'Cancelled',
                        'Your data is safe :)',
                        'error'
                    )
                }
            })
        }
    </script>
@endpush

resources/views/mobile/insert.blade.php
@extends('layouts.app')

@section('site-title', 'One to Many RelationShip')


@section('header-title', 'ONE TO MANY RELATIONSHIP')


@section('main-content')
    <div class="card">
        <div class="card-header bg-secondary">
            <h3 class="card-title">Insert Data</h3>
            <a href="{{ route('mobile.index') }}" class="btn btn-primary float-right" style="margin-top: -40px;">Back</a>
        </div>
        <div class="card-body">
            <form action="{{ route('mobile.store') }}" method="post">
                @csrf
                <div class="form-group row">
                    <label for="number" class="col-sm-2 col-form-label">Number</label>
                    <div class="col-sm-10">
                        <input type="tel" name="phone" class="form-control" id="number" value="{{ old('ticket') }}" placeholder="Number">
                    </div>
                </div>

                <div class="form-group row">
                    <label for="user" class="col-sm-2 col-form-label">User</label>
                    <div class="col-sm-10">
                        <select name="user" id="user" class="custom-select my-1 mr-sm-2">
                            <option selected disabled>Choose...</option>
                                @forelse($users as $user)
                                    <option value="{{ $user->id }}">{{ $user->name }}</option>
                                @empty
                                    <option disabled>No data found!!</option>
                                @endforelse
                        </select>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-sm-10">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </div>
            <form/>
        </div>
    </div>
@endsection

resources/views/mobile/show.blade.php
@extends('layouts.app')

@section('site-title', 'One to Many RelationShip')


@section('header-title', 'ONE TO MANY RELATIONSHIP')


@section('main-content')
    <div class="card">
        <div class="card-header bg-secondary">
            <h3 class="card-title">Show Data</h3>
            <a href="{{ route('mobile.index') }}" class="btn btn-primary float-right" style="margin-top: -40px;">Back</a>
        </div>
        <div class="card-body">
            <h1>Number: {{ $mobile->number }}</h1>
            <h3>User: {{ $mobile->user->name }}</h3>
            <a href="{{ route('mobile.edit', $mobile->id) }}" class="btn btn-primary">Edit</a>
        </div>
    </div>
@endsection

resources/views/show.blade.php
@extends('layouts.app')

@section('site-title', 'One to Many RelationShip')


@section('header-title', 'ONE TO MANY RELATIONSHIP')


@section('main-content')
    <div class="card">
        <div class="card-header bg-secondary">
            <h3 class="card-title">Show Data</h3>
            <a href="{{ route('index') }}" class="btn btn-primary float-right" style="margin-top: -40px;">Back</a>
        </div>
        <div class="card-body">
            @if (!empty($user))
                <h1>Name: {{ $user->name }}</h1>
            @else
                <h1>Name: No data found!</h1>
            @endif

            <h3>Numbers:</h3>
            @forelse($user->mobiles as $number)
                <ul>
                    <li>{{ $number->number }}</li>
                </ul>
            @empty
                <h3>Numbers: No data found!</h3>
            @endforelse

            <a href="{{ route('user.edit', $user->id) }}" class="btn btn-primary">Edit</a>
        </div>
    </div>
@endsection